Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.4"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "../", "/vagrant"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

config.vm.provision "shell", inline: <<-SHELL
    yum install -y yum-utils rsync
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum-config-manager --enable docker-ce-edge
    yum makecache fast
    yum install -y docker-ce
    systemctl start docker
    systemctl enable docker
    yum install -y epel-release
    yum install -y python-pip
    yum install -y python-devel
    yum install -y nano
    sudo usermod -a -G docker vagrant

SHELL

end
